### ISSUE TITLE
[BUG] in boot_panel tests_i is not on the output list for do_tests_and_bootstrap() function 

### ISSUE THREAD

**Issue by ASemeyutin** [smeekes/bootUR#5]
Hi

Encountered a problem with boot_panel() when deterministics = "intercept" or deterministics = "trend" for non union tests: 

"Error in rowMeans(inputs$tests_i):
        'x' must be an array of at least two dimensions."

I think that the problem is that the boot_panel() function has a line:

GM_test <- rowMeans(inputs$tests_i)

However, by looking into the do_tests_and_bootstrap() closely it has no output in the list named "tests_i". Shall it be changed to:

 GM_test <- rowMeans(inputs$indiv_par_est)

or any other actual outputs for do_testsand_bootstrap()?

Recently updated the package and my old code that was working fine until the update throws the above error. 

Kindest regards
Artur

**Comment by smeekes** [comment]
Yes, you are right, we asked for a non-existing element in the list. I corrected the version on GitHub; I will also send an update to CRAN soon.
